[book]
authors = ["kingdom-of-ds-hacking"]
language = "en"
multilingual = false
src = "src"
title = "Kingdom of DS Hacking"

[output.html.fold]
enable = true     # whether or not to enable section folding
level = 0         # the depth to start folding
